### ISSUE TITLE
Notekit è disponibile anche per Windows

### ISSUE THREAD

**Issue by Torkin1** [MaterialeIngegneriaFree/materiale-ingegneria-free#2]
Ciao! Vorrei segnalare che il software Notekit è disponibile anche per [Windows](http://twilightro.kafuka.org/~blackhole89/files/notekit-20210422.zip), mentre nel vostro sito è citata solo Linux come piattaforma.

**Comment by f-dinucci** [comment]
Grazie della segnalazione e scusa per il ritardo.
Al momento non l'abbiamo elencato poiché si tratta di una build "non ufficiale", slegata dal progetto in sé
